import { Suspense } from "react";
import "../styles/globals.css";
import { NavbarComponent } from "./components/Navbar";
import { Providers } from "./Providers";
import { InfoSocietyProvider } from "./context/InfoSocietyContext";
import { AuthProvider } from "./context/AuthContext";
import { TriangleAlert } from "lucide-react";
import AffProvider from "./context/AffContext";
import { readAffiliateCookie } from "./utils/aff";
import { GlobalProvider } from "./context/GlobalContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const aff = readAffiliateCookie(); // server-side

  const isDemo = process.env.NEXT_PUBLIC_DEMO === "true";
  return (
    <html suppressHydrationWarning lang="en">
      <body className="min-h-screen bg-background">
        <GlobalProvider>
          <AffProvider initial={aff}>
            <InfoSocietyProvider>
              <Providers
                themeProps={{ attribute: "data-theme", defaultTheme: "light" }}
              >
                <AuthProvider>
                  <Suspense fallback={<div>Loading...</div>}>
                    {isDemo && (
                      <div className="w-screen relative top-0 h-10 bg-danger z-50 flex items-center justify-center text-white text-sm uppercase gap-5">
                        <TriangleAlert size={24} />
                        {"Demo Mode"}
                      </div>
                    )}
                    <NavbarComponent />
                    {children}
                  </Suspense>
                </AuthProvider>
              </Providers>
            </InfoSocietyProvider>
          </AffProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
