import { Suspense } from "react";
import "../styles/globals.css";
import { NavbarComponent } from "./components/Navbar";

import { Providers } from "./Providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (typeof window !== "undefined" && typeof window.btoa === "undefined") {
    return null;
  }
  return (
    <html lang="en">
      <body className="min-h-screen bg-background">
        <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
          <Suspense fallback={<div>Loading...</div>}>
            <NavbarComponent />
            {children}
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
