import { Suspense } from "react";
import "../styles/globals.css";
import { NavbarComponent } from "./components/Navbar";
import { Providers } from "./Providers";
import { InfoSocietyProvider } from "./context/InfoSocietyContext";
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className="min-h-screen bg-background">
        <InfoSocietyProvider>
          <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
            <AuthProvider>
              <Suspense fallback={<div>Loading...</div>}>
                <NavbarComponent />
                {children}
              </Suspense>
            </AuthProvider>
          </Providers>
        </InfoSocietyProvider>
      </body>
    </html>
  );
}
